In [1]:
import pandas as pd
import json
import os

# First with 20,000 Steps and around 10 N for Timeout 60

## Single Core and on GPU

In [11]:
# This is for trial with one core at a time or n_jobs=1
trial_id = 435703
output_path = os.path.join("output", str(trial_id))
with open(os.path.join(output_path, "config.json"), "r") as f:
    config = json.load(f)
print("Config:", config)
df = pd.read_csv(os.path.join(output_path, "trials_results.csv"))
print(df.shape)
df

Config: {'steps': 20000, 'N': 3, 'target_node_count': 2, 'timeout': 60}
(8, 21)

,number,values_0,values_1,datetime_start,datetime_complete,duration,params_between_rest_spread,params_c_spread,params_c_val,params_input_force,...,params_k_between_val,params_k_wall_spread,params_k_wall_val,params_m_spread,params_m_val,params_ridge_alpha,params_wall_rest_spread,user_attrs_trial_seed,system_attrs_NSGAIISampler:generation,state
0,0,-1.998091,3.437603e+08,2026-07-24 01:50:14.036223,2026-07-24 01:50:22.143559,0 days 00:00:08.107336,0.656379,0.228246,0.118402,27.512590,...,10.218464,0.755932,7.425566,0.707896,0.008794,0.003813,0.500041,191664963,0,COMPLETE
1,1,-1.997136,2.588322e+08,2026-07-24 01:50:22.143665,2026-07-24 01:50:30.212265,0 days 00:00:08.068600,0.800343,1.082223,0.138948,27.094433,...,8.828893,0.778641,5.090588,0.243804,0.005580,0.010267,0.694754,1662057957,0,COMPLETE
2,2,0.062431,9.770060e-01,2026-07-24 01:50:30.212356,2026-07-24 01:50:38.275707,0 days 00:00:08.063351,0.183444,0.377922,0.177159,26.270590,...,23.533500,0.092292,48.918972,0.672211,0.098820,1.254768,0.445723,1405681631,0,COMPLETE
3,3,-1.999909,9.166701e+08,2026-07-24 01:50:38.275790,2026-07-24 01:50:46.529868,0 days 00:00:08.254078,0.653484,1.397633,0.213479,33.692276,...,29.997110,0.281104,23.971021,1.087036,0.012731,0.000002,0.251655,942484272,0,COMPLETE
4,4,0.031668,9.929052e-01,2026-07-24 01:50:46.529918,2026-07-24 01:50:54.638880,0 days 00:00:08.108962,1.155963,1.314690,0.028747,3.526731,...,37.038304,0.654375,4.116322,1.292831,0.019573,0.200611,0.703788,929893137,0,COMPLETE
5,5,-1.993591,1.349746e+08,2026-07-24 01:50:54.638947,2026-07-24 01:51:02.780239,0 days 00:00:08.141292,0.030905,0.188373,0.163907,23.206600,...,1.265071,0.433532,73.169115,1.497072,0.020406,0.000008,0.808775,1843824992,0,COMPLETE
6,6,-1.780874,4.542844e+06,2026-07-24 01:51:02.780284,2026-07-24 01:51:10.923769,0 days 00:00:08.143485,1.378892,0.442343,0.010322,10.154759,...,15.576535,0.552610,1.984140,0.633349,0.039085,0.000016,1.080060,184566854,0,COMPLETE
7,7,-1.965456,2.813424e+07,2026-07-24 01:51:10.923830,2026-07-24 01:51:19.016118,0 days 00:00:08.092288,0.215973,1.156921,0.175595,40.199099,...,7.989664,0.500136,2.184311,1.002608,0.086663,0.000001,0.248348,1497586438,0,COMPLETE

In [10]:
# This is for trial with one core at a time or n_jobs=1
trial_id = 435709
output_path = os.path.join("output", str(trial_id))
with open(os.path.join(output_path, "config.json"), "r") as f:
    config = json.load(f)
print("Config:", config)
df = pd.read_csv(os.path.join(output_path, "trials_results.csv"))
print(df.shape)
df

Config: {'steps': 20000, 'N': 12, 'target_node_count': 3, 'timeout': 60}
(8, 21)

,number,values_0,values_1,datetime_start,datetime_complete,duration,params_between_rest_spread,params_c_spread,params_c_val,params_input_force,...,params_k_between_val,params_k_wall_spread,params_k_wall_val,params_m_spread,params_m_val,params_ridge_alpha,params_wall_rest_spread,user_attrs_trial_seed,system_attrs_NSGAIISampler:generation,state
0,0,-1.999818,8.461598e+08,2026-07-24 02:13:48.093378,2026-07-24 02:13:56.256248,0 days 00:00:08.162870,0.696648,0.556999,0.103017,8.419554,...,66.694841,1.134027,59.548115,0.608022,0.009501,2.181393,0.300397,191664963,0,COMPLETE
1,1,-1.999909,9.166701e+08,2026-07-24 02:13:56.256356,2026-07-24 02:14:04.414459,0 days 00:00:08.158103,0.501519,1.136962,0.216498,20.433708,...,42.005525,0.335853,8.573463,1.274728,0.002476,0.030401,0.515620,1662057957,0,COMPLETE
2,2,-1.999773,8.148217e+08,2026-07-24 02:14:04.414557,2026-07-24 02:14:12.515865,0 days 00:00:08.101308,1.454927,0.814811,0.184319,20.580334,...,1.622166,0.558640,2.045848,0.865673,0.009175,0.000137,0.135350,1405681631,0,COMPLETE
3,3,0.281521,8.552692e-01,2026-07-24 02:14:12.515940,2026-07-24 02:14:20.655826,0 days 00:00:08.139886,1.454859,1.302149,0.295042,42.134300,...,79.430058,1.364856,26.134211,0.317316,0.086418,0.000015,0.107884,942484272,0,COMPLETE
4,4,0.478939,7.283497e-01,2026-07-24 02:14:20.655899,2026-07-24 02:14:28.945091,0 days 00:00:08.289192,1.352781,1.312023,0.374054,8.241266,...,1.992495,0.845595,59.949846,0.834324,0.014025,7.511361,1.121789,929893137,0,COMPLETE
5,5,-1.643789,2.799465e+06,2026-07-24 02:14:28.945139,2026-07-24 02:14:37.127577,0 days 00:00:08.182438,1.337291,1.238528,0.055245,30.331727,...,13.906893,0.287205,8.746469,0.684212,0.062896,0.004163,0.363234,1843824992,0,COMPLETE
6,6,-1.997091,2.558226e+08,2026-07-24 02:14:37.127638,2026-07-24 02:14:45.309484,0 days 00:00:08.181846,0.712211,0.275683,0.050010,49.548970,...,4.825046,0.345753,1.895894,0.480516,0.053046,0.000015,0.246501,184566854,0,COMPLETE
7,7,-1.999955,9.565236e+08,2026-07-24 02:14:45.309526,2026-07-24 02:14:53.543683,0 days 00:00:08.234157,0.065044,1.483523,0.050067,45.968099,...,8.129654,0.941278,54.205164,0.950697,0.001176,8.396559,0.430252,1497586438,0,COMPLETE

## 4 GPU's

In [12]:
# This one is for trial with 4 gpu's
trial_id = 435715
output_path = os.path.join("output", str(trial_id))
with open(os.path.join(output_path, "config.json"), "r") as f:
    config = json.load(f)
print("Config:", config)
df = pd.read_csv(os.path.join(output_path, "trials_results.csv"))
print(df.shape)
df[:10]

Config: {'steps': 20000, 'N': 12, 'target_node_count': 3, 'timeout': 60}
(31, 21)

,number,values_0,values_1,datetime_start,datetime_complete,duration,params_between_rest_spread,params_c_spread,params_c_val,params_input_force,...,params_k_between_val,params_k_wall_spread,params_k_wall_val,params_m_spread,params_m_val,params_ridge_alpha,params_wall_rest_spread,user_attrs_trial_seed,system_attrs_NSGAIISampler:generation,state
0,0,-1.999864,8.800048e+08,2026-07-24 02:24:28.944940,2026-07-24 02:24:38.244605,0 days 00:00:09.299665,0.912567,0.617326,0.033199,34.560792,...,23.058995,0.244522,71.349164,1.357171,0.041739,0.001379,0.844755,191664963,0,COMPLETE
1,1,-1.999955,9.565236e+08,2026-07-24 02:24:29.060657,2026-07-24 02:24:38.339485,0 days 00:00:09.278828,0.595300,0.524649,0.071574,45.748562,...,5.495338,0.654225,4.109001,0.467465,0.001287,13.032010,1.223367,191664963,0,COMPLETE
2,2,0.111182,9.512661e-01,2026-07-24 02:24:29.589320,2026-07-24 02:24:38.460695,0 days 00:00:08.871375,0.326032,0.464382,0.062994,30.605879,...,89.595795,0.182765,7.578611,0.013027,0.049148,0.021909,1.390864,191664963,0,COMPLETE
3,3,-1.583610,2.395840e+06,2026-07-24 02:24:29.589597,2026-07-24 02:24:38.548699,0 days 00:00:08.959102,0.772907,0.824089,0.055252,17.062658,...,15.719267,0.414882,5.441012,0.426335,0.057699,80.815765,0.632948,191664963,0,COMPLETE
4,4,-1.996546,2.244977e+08,2026-07-24 02:24:38.257707,2026-07-24 02:24:46.676595,0 days 00:00:08.418888,0.259554,1.431514,0.016885,27.074634,...,11.403796,0.126796,41.703697,0.168099,0.022081,0.305498,0.170944,1662057957,0,COMPLETE
5,5,-1.999182,5.500112e+08,2026-07-24 02:24:38.349642,2026-07-24 02:24:46.596648,0 days 00:00:08.247006,1.391537,0.078670,0.010614,9.676396,...,3.666191,0.354030,32.779005,0.413291,0.056504,8.979477,0.838041,1662057957,0,COMPLETE
6,6,-1.999909,9.166701e+08,2026-07-24 02:24:38.471483,2026-07-24 02:24:46.853637,0 days 00:00:08.382154,1.340837,1.072404,0.489120,33.152247,...,14.322733,0.578593,5.711467,0.279933,0.003075,0.019424,0.203271,1662057957,0,COMPLETE
7,7,-1.999182,5.500112e+08,2026-07-24 02:24:38.558768,2026-07-24 02:24:46.990510,0 days 00:00:08.431742,1.341665,1.469921,0.015687,42.827138,...,42.659504,1.495025,2.703319,1.264004,0.066781,0.197998,1.226161,1662057957,0,COMPLETE
8,8,-1.999864,8.800048e+08,2026-07-24 02:24:46.605954,2026-07-24 02:24:55.031064,0 days 00:00:08.425110,0.448762,0.074239,0.180022,12.258719,...,39.138186,0.535672,10.425321,0.544982,0.011303,9.299373,1.385402,1405681631,0,COMPLETE
9,9,-1.999727,7.857219e+08,2026-07-24 02:24:46.686102,2026-07-24 02:24:55.274118,0 days 00:00:08.588016,1.340936,1.168184,0.453866,4.817705,...,1.029416,0.649887,41.456584,1.186116,0.031771,0.000005,0.617310,1405681631,0,COMPLETE

In [6]:
# So 4 min since 4 gpu's even though real time is 1 min
pd.to_timedelta(df['duration']).sum()

Timedelta('0 days 00:04:23.481494')

## N Cpu's

In [9]:
# This one is for trial with 4 gpu's
trial_id = 435750
output_path = os.path.join("output", str(trial_id))
with open(os.path.join(output_path, "config.json"), "r") as f:
    config = json.load(f)
print("Config:", config)
df = pd.read_csv(os.path.join(output_path, "trials_results.csv"))
print(df.shape)
df[:10]

Config: {'steps': 20000, 'N': 12, 'target_node_count': 3, 'timeout': 60}
(341, 21)

,number,values_0,values_1,datetime_start,datetime_complete,duration,params_between_rest_spread,params_c_spread,params_c_val,params_input_force,...,params_k_between_val,params_k_wall_spread,params_k_wall_val,params_m_spread,params_m_val,params_ridge_alpha,params_wall_rest_spread,user_attrs_trial_seed,system_attrs_NSGAIISampler:generation,state
0,0,-1.999955,9.565236e+08,2026-07-24 10:40:44.303653,2026-07-24 10:40:52.211052,0 days 00:00:07.907399,1.095915,1.054449,0.055734,3.005429,...,46.773960,0.214426,1.749078,1.251389,0.001614,0.000362,0.281956,191664963,0,COMPLETE
1,1,-1.999955,9.565236e+08,2026-07-24 10:40:44.304079,2026-07-24 10:40:51.815427,0 days 00:00:07.511348,1.127380,0.695735,0.030146,21.393221,...,61.082614,0.090507,2.414520,0.219666,0.002737,0.223997,1.078359,1405681631,0,COMPLETE
2,2,-1.999955,9.565236e+08,2026-07-24 10:40:44.304456,2026-07-24 10:40:53.599682,0 days 00:00:09.295226,0.988893,1.452753,0.874995,44.342574,...,3.984504,1.160398,50.767689,1.478744,0.003497,0.000070,1.340133,1662057957,0,COMPLETE
3,3,-1.992409,1.164068e+08,2026-07-24 10:40:44.305187,2026-07-24 10:40:52.803278,0 days 00:00:08.498091,0.234808,0.167798,0.012573,14.863990,...,81.649109,1.102580,18.385869,1.231776,0.073760,36.154975,0.611480,942484272,0,COMPLETE
4,4,-1.999727,7.857219e+08,2026-07-24 10:40:44.306113,2026-07-24 10:40:52.803666,0 days 00:00:08.497553,0.627908,1.087732,0.289423,40.238732,...,7.720551,1.282724,7.366480,0.089994,0.008308,0.533146,1.181251,929893137,0,COMPLETE
5,5,-1.997546,2.894830e+08,2026-07-24 10:40:44.306822,2026-07-24 10:40:53.202097,0 days 00:00:08.895275,1.328840,1.190076,0.169582,21.696940,...,11.849619,0.307768,49.736093,1.223318,0.023269,6.824396,0.230498,1843824992,0,COMPLETE
6,6,-1.999864,8.800048e+08,2026-07-24 10:40:44.307169,2026-07-24 10:40:53.399853,0 days 00:00:09.092684,0.866356,0.735696,0.026093,46.283300,...,4.978995,1.064039,1.153612,0.736460,0.006145,0.000804,0.115143,184566854,0,COMPLETE
7,7,-1.999955,9.565236e+08,2026-07-24 10:40:44.307828,2026-07-24 10:40:53.399031,0 days 00:00:09.091203,0.774326,0.421213,0.058572,8.986346,...,14.121626,0.707972,12.397635,0.825883,0.001644,0.001699,0.459636,432652533,0,COMPLETE
8,8,-1.919140,1.221598e+07,2026-07-24 10:40:44.308344,2026-07-24 10:40:53.201793,0 days 00:00:08.893449,0.687982,0.603374,0.807850,32.304752,...,3.329964,0.969675,10.194745,0.176290,0.011244,0.023071,0.714570,1497586438,0,COMPLETE
9,9,-1.999864,8.800048e+08,2026-07-24 10:40:44.309462,2026-07-24 10:40:52.803794,0 days 00:00:08.494332,0.627462,0.690703,0.199234,14.593184,...,70.018486,0.274088,1.365561,0.692495,0.024863,0.000006,0.623683,202244314,0,COMPLETE

In [8]:
# So 4 min since 4 gpu's even though real time is 1 min
pd.to_timedelta(df['duration']).sum()

Timedelta('0 days 01:04:52.667986')

# 100,000 steps and N is 1000 and timeout is 150

In [2]:
def print_memory_estimate(steps, num_nodes, dims):
    matrix_size = num_nodes * dims
    bytes_per_float = 8
    # disp, v, and U matrices
    total_bytes = (steps * matrix_size * bytes_per_float) * 3 
    total_gb = total_bytes / (1024**3)
    print(f"Memory required for ONE trial simulation: {total_gb:.2f} GB")
    print(f"Memory required if running 50 concurrent cores: {total_gb * 50:.2f} GB")

print_memory_estimate(steps=100_000, num_nodes=1000, dims=2)

Memory required for ONE trial simulation: 4.47 GB
Memory required if running 50 concurrent cores: 223.52 GB

## 4 GPU

In [ ]:
trial_id = 435760
output_path = os.path.join("output", str(trial_id))
with open(os.path.join(output_path, "config.json"), "r") as f:
    config = json.load(f)
print("Config:", config)
df = pd.read_csv(os.path.join(output_path, "trials_results.csv"))
print(df.shape)
df[:10]

Config: {'steps': 100000, 'N': 1000, 'target_node_count': 100, 'timeout': 150}
(15, 21)

,number,values_0,values_1,datetime_start,datetime_complete,duration,params_between_rest_spread,params_c_spread,params_c_val,params_input_force,...,params_k_between_val,params_k_wall_spread,params_k_wall_val,params_m_spread,params_m_val,params_ridge_alpha,params_wall_rest_spread,user_attrs_trial_seed,system_attrs_NSGAIISampler:generation,state
0,0,-1.999991,9.909911e+08,2026-07-24 11:05:58.268062,2026-07-24 11:06:45.170506,0 days 00:00:46.902444,0.702501,0.776826,0.090492,3.944122,...,1.327259,1.232266,89.159829,1.237064,0.003263,0.000001,0.888746,191664963,0,COMPLETE
1,1,-1.999991,9.909911e+08,2026-07-24 11:05:58.424809,2026-07-24 11:06:45.760649,0 days 00:00:47.335840,0.520480,0.309291,0.049296,27.275746,...,12.878147,1.474158,84.683009,1.254503,0.030533,0.004765,0.086696,191664963,0,COMPLETE
2,2,-1.999991,9.909911e+08,2026-07-24 11:05:58.560479,2026-07-24 11:06:45.440399,0 days 00:00:46.879920,0.970235,1.058192,0.201274,3.596085,...,10.917963,0.942436,1.287643,0.656311,0.002573,0.000616,0.380733,191664963,0,COMPLETE
3,3,-1.999991,9.909911e+08,2026-07-24 11:05:58.560752,2026-07-24 11:06:45.319316,0 days 00:00:46.758564,0.563710,0.580028,0.016741,28.407430,...,71.265162,1.178274,35.934363,0.745103,0.084807,0.000060,1.162564,191664963,0,COMPLETE
4,4,-1.999991,9.909911e+08,2026-07-24 11:06:45.182233,2026-07-24 11:07:27.310087,0 days 00:00:42.127854,0.886561,0.844925,0.101049,33.564754,...,24.067644,0.064093,2.703108,1.309367,0.007395,0.436346,1.124040,1662057957,0,COMPLETE
5,5,-1.999991,9.909911e+08,2026-07-24 11:06:45.329386,2026-07-24 11:07:28.592196,0 days 00:00:43.262810,0.544641,1.363749,0.736242,39.939998,...,9.415247,0.107689,20.026299,0.391168,0.001508,0.000012,0.385531,1662057957,0,COMPLETE
6,6,-1.999991,9.909911e+08,2026-07-24 11:06:45.450716,2026-07-24 11:07:27.465358,0 days 00:00:42.014642,1.118431,1.102546,0.972794,29.282274,...,11.119672,0.877901,35.555245,0.855907,0.005081,4.741304,0.502377,1662057957,0,COMPLETE
7,7,-1.999991,9.909911e+08,2026-07-24 11:06:45.772771,2026-07-24 11:07:28.057741,0 days 00:00:42.284970,0.412337,0.795485,0.033435,40.911768,...,90.736606,0.513285,36.590795,0.187111,0.019384,0.005779,0.636533,1662057957,0,COMPLETE
8,8,-1.999991,9.909911e+08,2026-07-24 11:07:27.320781,2026-07-24 11:08:09.584282,0 days 00:00:42.263501,0.837524,1.251704,0.420500,19.104806,...,52.987849,0.717736,9.545035,1.469407,0.001697,0.000003,1.482029,1405681631,0,COMPLETE
9,9,NaN,NaN,2026-07-24 11:07:27.474943,2026-07-24 11:07:27.871625,0 days 00:00:00.396682,0.097280,0.890241,0.048822,31.184112,...,11.753258,0.859103,34.769896,0.342467,0.001780,0.099738,0.432507,1405681631,0,FAIL
10,10,-1.999991,9.909911e+08,2026-07-24 11:07:28.067789,2026-07-24 11:08:10.816139,0 days 00:00:42.748350,0.581244,0.797951,0.443385,18.541311,...,33.452051,0.918147,2.310290,1.414853,0.012385,1.213767,1.193518,1405681631,0,COMPLETE
11,11,-1.999991,9.909911e+08,2026-07-24 11:07:28.603057,2026-07-24 11:08:10.547853,0 days 00:00:41.944796,0.122476,0.363558,0.041298,38.978485,...,68.979495,0.560198,15.892641,1.107492,0.024446,0.000561,0.535033,1405681631,0,COMPLETE
12,12,-1.999991,9.909911e+08,2026-07-24 11:08:09.594492,2026-07-24 11:08:51.412434,0 days 00:00:41.817942,0.361800,1.213266,0.077500,13.101880,...,4.455155,0.067162,4.529651,0.683182,0.001622,0.000005,0.659034,942484272,0,COMPLETE
13,13,-1.999991,9.909911e+08,2026-07-24 11:08:10.557044,2026-07-24 11:08:53.579733,0 days 00:00:43.022689,1.121645,0.903574,0.640173,7.162227,...,9.122225,0.296639,1.103621,0.695799,0.035141,0.020508,0.096929,942484272,0,COMPLETE
14,14,-1.999991,9.909911e+08,2026-07-24 11:08:10.826285,2026-07-24 11:08:53.057442,0 days 00:00:42.231157,0.958828,0.641913,0.013785,11.431652,...,5.759716,0.682185,67.139576,0.589595,0.001202,0.000814,1.364839,942484272,0,COMPLETE

In [11]:
trial_id = 435769
output_path = os.path.join("output", str(trial_id))
with open(os.path.join(output_path, "config.json"), "r") as f:
    config = json.load(f)
print("Config:", config)
df_res = pd.read_csv(os.path.join(output_path, "trials_results.csv"))
print(df_res.shape)
df_res[:10]

Config: {'steps': 100000, 'N': 1000, 'target_node_count': 100, 'timeout': 5400}
(263, 21)

,number,values_0,values_1,datetime_start,datetime_complete,duration,params_between_rest_spread,params_c_spread,params_c_val,params_input_force,...,params_k_between_val,params_k_wall_spread,params_k_wall_val,params_m_spread,params_m_val,params_ridge_alpha,params_wall_rest_spread,user_attrs_trial_seed,system_attrs_NSGAIISampler:generation,state
0,0,-1.999918,9.243704e+08,2026-07-24 11:22:58.100527,2026-07-24 11:23:43.172141,0 days 00:00:45.071614,0.173345,0.542072,0.068198,28.584245,...,1.057600,0.399266,1.407250,0.565808,0.042639,0.040601,1.498567,191664963,0,COMPLETE
1,1,-1.999982,9.821430e+08,2026-07-24 11:22:58.374089,2026-07-24 11:23:46.645055,0 days 00:00:48.270966,0.573427,0.677259,0.954133,16.269074,...,25.777592,0.032901,46.988341,0.177094,0.097700,0.000002,1.496918,191664963,0,COMPLETE
2,2,-1.999991,9.909911e+08,2026-07-24 11:22:58.439340,2026-07-24 11:23:45.068731,0 days 00:00:46.629391,1.179438,0.679748,0.411169,3.605121,...,8.523423,0.575851,5.683722,0.700294,0.001557,0.000088,0.104633,191664963,0,COMPLETE
3,3,-1.999991,9.909911e+08,2026-07-24 11:22:58.542504,2026-07-24 11:23:45.985551,0 days 00:00:47.443047,0.748296,1.170281,0.033513,45.647869,...,6.257499,0.769121,14.825698,1.168606,0.023097,0.009059,0.119399,191664963,0,COMPLETE
4,4,-1.999955,9.565221e+08,2026-07-24 11:23:43.184115,2026-07-24 11:24:25.657277,0 days 00:00:42.473162,0.478334,0.947799,0.322632,20.121967,...,4.250286,0.685097,2.029907,0.688349,0.083698,0.001211,0.130660,1662057957,0,COMPLETE
5,5,-1.999991,9.909911e+08,2026-07-24 11:23:45.079122,2026-07-24 11:24:28.811440,0 days 00:00:43.732318,1.232551,1.483410,0.642615,26.010128,...,11.945227,0.756689,37.664911,0.781110,0.007542,0.000685,0.857116,1662057957,0,COMPLETE
6,6,-1.999982,9.821430e+08,2026-07-24 11:23:45.996925,2026-07-24 11:24:29.453891,0 days 00:00:43.456966,0.997468,1.048534,0.552459,41.460453,...,1.286346,1.449107,1.018084,1.091668,0.070979,0.001455,0.984600,1662057957,0,COMPLETE
7,7,-1.999991,9.909911e+08,2026-07-24 11:23:46.658253,2026-07-24 11:24:31.009097,0 days 00:00:44.350844,0.339714,0.674042,0.013430,26.458241,...,6.064021,1.106083,1.904386,0.420291,0.001838,0.021688,0.440458,1662057957,0,COMPLETE
8,8,-1.999991,9.909911e+08,2026-07-24 11:24:25.668498,2026-07-24 11:25:08.114157,0 days 00:00:42.445659,0.388988,0.749174,0.066141,4.291639,...,13.789234,0.670035,51.364794,0.190799,0.002590,3.004728,1.186387,1405681631,0,COMPLETE
9,9,-1.999991,9.909911e+08,2026-07-24 11:24:28.821712,2026-07-24 11:25:12.345749,0 days 00:00:43.524037,0.826007,0.803712,0.142160,2.640123,...,13.603459,0.503577,10.746640,1.093277,0.023378,14.318730,0.247907,1405681631,0,COMPLETE

In [ ]:
df_best = pd.read_csv(os.path.join(output_path, "best_results.csv"))
df_best

   number  input_force        r2       mse
0     225    26.701374  0.591293  0.638992

In [12]:
df_res.loc[df_res['state'] != 'COMPLETE']

,number,values_0,values_1,datetime_start,datetime_complete,duration,params_between_rest_spread,params_c_spread,params_c_val,params_input_force,...,params_k_between_val,params_k_wall_spread,params_k_wall_val,params_m_spread,params_m_val,params_ridge_alpha,params_wall_rest_spread,user_attrs_trial_seed,system_attrs_NSGAIISampler:generation,state
13,13,NaN,NaN,2026-07-24 11:25:11.924743,2026-07-24 11:25:12.324291,0 days 00:00:00.399548,0.611379,0.131514,0.032786,3.025749,...,16.605125,1.406859,1.041226,1.155847,0.015305,0.000005,0.794647,942484272,0,FAIL
22,22,NaN,NaN,2026-07-24 11:27:16.503055,2026-07-24 11:27:16.918645,0 days 00:00:00.415590,0.582684,0.033137,0.031376,2.079713,...,7.714925,0.424617,13.199544,0.825910,0.015010,8.615891,0.521930,184566854,0,FAIL

# 100,000 steps and N is 100 and timeout is 60

## 32 cpu's run for a single time

In [ ]:
trial_id = 435841
output_path = os.path.join("output", str(trial_id))
with open(os.path.join(output_path, "config.json"), "r") as f:
    config = json.load(f)
print("Config:", config)
df = pd.read_csv(os.path.join(output_path, "trials_results.csv"))
print(df.shape)
df[:10]

Config: {'steps': 100000, 'N': 100, 'target_node_count': 10, 'timeout': 60}
(32, 21)

,number,values_0,values_1,datetime_start,datetime_complete,duration,params_between_rest_spread,params_c_spread,params_c_val,params_input_force,...,params_k_between_val,params_k_wall_spread,params_k_wall_val,params_m_spread,params_m_val,params_ridge_alpha,params_wall_rest_spread,user_attrs_trial_seed,system_attrs_NSGAIISampler:generation,state
0,0,-1.999982,9.821430e+08,2026-07-24 14:57:57.406081,2026-07-24 15:01:00.762668,0 days 00:03:03.356587,1.433197,0.633565,0.180313,8.157498,...,1.024171,1.370442,5.608432,0.529515,0.006436,0.376343,0.331442,191664963,0,COMPLETE
1,1,-1.999991,9.909911e+08,2026-07-24 14:57:57.406443,2026-07-24 15:01:42.425774,0 days 00:03:45.019331,1.146638,0.083551,0.250620,39.121115,...,58.666759,1.498525,4.370751,0.792941,0.001223,0.052747,1.267558,1662057957,0,COMPLETE
2,2,-1.999991,9.909911e+08,2026-07-24 14:57:57.407535,2026-07-24 15:01:08.884679,0 days 00:03:11.477144,1.004086,1.109652,0.284042,29.142940,...,11.912492,0.358149,54.046881,1.060512,0.001133,0.176558,1.088892,1405681631,0,COMPLETE
3,3,-1.999991,9.909911e+08,2026-07-24 14:57:57.408198,2026-07-24 15:01:42.432551,0 days 00:03:45.024353,0.892153,0.324965,0.025645,12.267804,...,1.571239,0.115826,11.875233,1.015821,0.001357,0.000005,0.738458,942484272,0,COMPLETE
4,4,-1.999991,9.909911e+08,2026-07-24 14:57:57.408849,2026-07-24 15:01:34.032614,0 days 00:03:36.623765,1.489990,0.128299,0.022574,4.534195,...,54.380314,0.977951,6.408043,1.286337,0.004991,0.272851,1.050233,929893137,0,COMPLETE
5,5,-1.999991,9.909911e+08,2026-07-24 14:57:57.409418,2026-07-24 15:02:15.275433,0 days 00:04:17.866015,1.073198,0.257198,0.077387,21.774229,...,1.076545,0.506767,10.757313,1.089582,0.003084,18.630738,0.247684,1843824992,0,COMPLETE
6,6,-1.999955,9.565221e+08,2026-07-24 14:57:57.410075,2026-07-24 15:02:07.082204,0 days 00:04:09.672129,0.291493,0.568429,0.371194,26.250948,...,9.355150,0.685128,16.588060,0.025673,0.014253,21.116490,1.292136,184566854,0,COMPLETE
7,7,-1.999991,9.909911e+08,2026-07-24 14:57:57.410802,2026-07-24 15:02:23.584461,0 days 00:04:26.173659,0.581613,1.033814,0.281451,37.460098,...,16.122054,1.334970,1.125985,0.866171,0.009191,0.267923,0.587847,1497586438,0,COMPLETE
8,8,-1.999991,9.909911e+08,2026-07-24 14:57:57.411319,2026-07-24 15:02:23.698967,0 days 00:04:26.287648,0.455498,1.273940,0.034271,31.238131,...,64.991072,0.388304,4.424884,1.228512,0.099079,0.000027,0.953192,1130604997,0,COMPLETE
9,9,-1.999991,9.909911e+08,2026-07-24 14:57:57.411651,2026-07-24 15:02:23.596647,0 days 00:04:26.184996,0.986610,1.015415,0.165330,15.518102,...,12.387179,1.321360,2.408384,1.075321,0.002300,3.769349,1.156907,432652533,0,COMPLETE

## 4 GPU

In [ ]:
trial_id = 435853
output_path = os.path.join("output", str(trial_id))
with open(os.path.join(output_path, "config.json"), "r") as f:
    config = json.load(f)
print("Config:", config)
df = pd.read_csv(os.path.join(output_path, "trials_results.csv"))
print(df.shape)
df[:10]

Config: {'steps': 100000, 'N': 100, 'target_node_count': 10, 'timeout': 60}
(8, 20)

,number,values_0,values_1,datetime_start,datetime_complete,duration,params_between_rest_spread,params_c_spread,params_c_val,params_input_force,params_k_between_spread,params_k_between_val,params_k_wall_spread,params_k_wall_val,params_m_spread,params_m_val,params_ridge_alpha,params_wall_rest_spread,system_attrs_NSGAIISampler:generation,state
0,0,-1.999991,9.909911e+08,2026-07-24 16:25:03.869626,2026-07-24 16:25:53.776422,0 days 00:00:49.906796,0.309596,0.504876,0.204330,42.054803,0.245548,23.626518,0.205768,61.653526,1.025517,0.008887,0.001089,1.493090,0,COMPLETE
1,1,-1.999973,9.734516e+08,2026-07-24 16:25:03.888469,2026-07-24 16:25:55.571209,0 days 00:00:51.682740,0.205910,1.321086,0.226262,25.281728,1.296354,5.383198,0.535316,77.213911,0.258128,0.026043,5.422231,1.307613,0,COMPLETE
2,2,-1.999982,9.821430e+08,2026-07-24 16:25:03.918177,2026-07-24 16:25:50.428938,0 days 00:00:46.510761,1.086208,1.358436,0.340450,38.924643,1.197514,1.783877,0.734956,1.682662,1.220380,0.010818,0.000035,0.445088,0,COMPLETE
3,3,-1.999991,9.909911e+08,2026-07-24 16:25:04.061390,2026-07-24 16:25:55.777476,0 days 00:00:51.716086,0.742233,0.831665,0.517993,6.271639,0.094768,46.788270,0.450798,1.071687,0.664916,0.006402,0.000956,0.013399,0,COMPLETE
4,4,-1.999991,9.909911e+08,2026-07-24 16:25:50.440010,2026-07-24 16:26:35.757695,0 days 00:00:45.317685,1.039666,0.562043,0.100708,41.660130,0.011969,14.018584,0.466060,46.572812,0.136972,0.004691,0.000004,1.358452,0,COMPLETE
5,5,-1.999982,9.821430e+08,2026-07-24 16:25:53.785686,2026-07-24 16:26:37.164075,0 days 00:00:43.378389,0.352923,1.259675,0.353518,30.131522,0.973345,1.002561,1.024236,1.239174,1.061456,0.003845,0.396516,1.137013,0,COMPLETE
6,6,-1.999936,9.401715e+08,2026-07-24 16:25:55.580413,2026-07-24 16:26:39.596014,0 days 00:00:44.015601,0.495024,0.519595,0.021875,8.973326,0.857768,1.165039,1.015368,9.378187,0.425954,0.028355,0.000244,1.043368,0,COMPLETE
7,7,-1.999991,9.909911e+08,2026-07-24 16:25:55.792087,2026-07-24 16:26:42.071913,0 days 00:00:46.279826,0.522918,0.955588,0.884685,22.559280,0.415736,21.468693,0.389977,8.690083,0.020177,0.002203,1.609044,0.101028,0,COMPLETE

## Results

So it takes 45 seconds for a gpu to run it and I can 4 in a row

It takes 4 min for a cpu to run it but I can do 32 in a row

In 4 min I can have 5 gpu runs so we get 20 trials with gpu compared to 32 with cpu

But I checked aldo only takes 2.5gb of 46gb so if we cut of a gpu liek 45 divided by 3 you get 15. Then per gpu you could 4 * 15. So then for this we could do 32 * 15

In [3]:
print_memory_estimate(steps=100_000, num_nodes=100, dims=2)

Memory required for ONE trial simulation: 0.45 GB
Memory required if running 50 concurrent cores: 22.35 GB

# 100,000 steps and N is 300 and timeout is 60

## 32 cpu's run for a single time

In [7]:
trial_id = 435859
output_path = os.path.join("output", str(trial_id))
with open(os.path.join(output_path, "config.json"), "r") as f:
    config = json.load(f)
print("Config:", config)
df = pd.read_csv(os.path.join(output_path, "trials_results.csv"))
print(df.shape)
df[:10]

Config: {'steps': 100000, 'N': 300, 'target_node_count': 10, 'timeout': 60}
(30, 21)

,number,values_0,values_1,datetime_start,datetime_complete,duration,params_between_rest_spread,params_c_spread,params_c_val,params_input_force,...,params_k_between_val,params_k_wall_spread,params_k_wall_val,params_m_spread,params_m_val,params_ridge_alpha,params_wall_rest_spread,user_attrs_trial_seed,system_attrs_NSGAIISampler:generation,state
0,0,0.640380,5.993930e-01,2026-07-24 16:42:00.122613,2026-07-24 16:54:37.408780,0 days 00:12:37.286167,0.108196,0.292459,0.419554,17.365595,...,56.911718,0.710516,2.675345,0.520021,0.029097,0.063631,1.171574,191664963,0,COMPLETE
1,1,-1.999991,9.909911e+08,2026-07-24 16:42:00.135189,2026-07-24 16:54:36.600214,0 days 00:12:36.465025,0.677917,1.117737,0.238034,4.198889,...,14.365627,1.107441,39.815049,0.761219,0.001598,0.001567,0.642620,1662057957,0,COMPLETE
2,2,-1.999991,9.909911e+08,2026-07-24 16:42:00.158201,2026-07-24 16:54:36.588047,0 days 00:12:36.429846,1.094081,0.154458,0.188917,42.851740,...,21.229801,0.253196,25.979472,1.311792,0.080798,67.244283,0.512229,1405681631,0,COMPLETE
3,3,-1.999945,9.482763e+08,2026-07-24 16:42:00.196191,2026-07-24 16:54:37.254438,0 days 00:12:37.058247,0.488253,1.313478,0.019512,39.610555,...,2.487384,1.353540,1.157152,0.348066,0.015260,0.333472,0.627282,942484272,0,COMPLETE
4,4,-1.999991,9.909911e+08,2026-07-24 16:42:00.226196,2026-07-24 16:54:36.625049,0 days 00:12:36.398853,1.000681,0.915797,0.011077,20.409297,...,19.561818,1.321135,16.845870,1.331794,0.073161,0.311881,1.145946,929893137,0,COMPLETE
5,5,-1.999982,9.821430e+08,2026-07-24 16:42:00.241190,2026-07-24 16:54:36.528554,0 days 00:12:36.287364,0.422344,0.443646,0.561345,40.287850,...,1.578092,0.864801,1.896540,0.911667,0.004369,0.005238,0.065035,1843824992,0,COMPLETE
6,6,-1.999991,9.909911e+08,2026-07-24 16:42:00.282349,2026-07-24 16:54:37.199397,0 days 00:12:36.917048,1.336084,0.942552,0.400230,4.726963,...,9.184559,0.823618,22.784322,1.399777,0.001479,23.916206,0.055587,184566854,0,COMPLETE
7,7,-1.999991,9.909911e+08,2026-07-24 16:42:00.349530,2026-07-24 16:54:34.114401,0 days 00:12:33.764871,0.139054,0.737555,0.013307,30.643528,...,51.471523,0.749922,33.053350,0.710613,0.009153,86.502393,0.417263,1497586438,0,COMPLETE
8,8,-1.999982,9.821430e+08,2026-07-24 16:42:00.406001,2026-07-24 16:54:33.758645,0 days 00:12:33.352644,0.688861,1.293749,0.052991,9.672738,...,4.427284,1.078139,93.958889,0.210083,0.013215,0.000008,1.333957,432652533,0,COMPLETE
9,9,-1.999973,9.734516e+08,2026-07-24 16:42:00.438185,2026-07-24 16:54:32.931786,0 days 00:12:32.493601,0.716859,0.109143,0.930686,35.233773,...,3.386778,0.358193,2.667522,0.567833,0.007262,0.007010,1.082612,202244314,0,COMPLETE

## 4 GPU

In [5]:
trial_id = 435855
output_path = os.path.join("output", str(trial_id))
with open(os.path.join(output_path, "config.json"), "r") as f:
    config = json.load(f)
print("Config:", config)
df = pd.read_csv(os.path.join(output_path, "trials_results.csv"))
print(df.shape)
df[:10]

Config: {'steps': 100000, 'N': 300, 'target_node_count': 10, 'timeout': 60}
(8, 20)

,number,values_0,values_1,datetime_start,datetime_complete,duration,params_between_rest_spread,params_c_spread,params_c_val,params_input_force,params_k_between_spread,params_k_between_val,params_k_wall_spread,params_k_wall_val,params_m_spread,params_m_val,params_ridge_alpha,params_wall_rest_spread,system_attrs_NSGAIISampler:generation,state
0,0,-1.999964,9.649126e+08,2026-07-24 16:30:27.208123,2026-07-24 16:31:13.793952,0 days 00:00:46.585829,0.452537,0.213420,0.018485,2.227079,0.151414,7.041859,0.012363,21.783187,1.265909,0.098341,0.000008,1.076305,0,COMPLETE
1,1,-1.999991,9.909911e+08,2026-07-24 16:30:27.373306,2026-07-24 16:31:11.806206,0 days 00:00:44.432900,0.811767,1.473117,0.281362,33.908339,0.081829,7.055857,0.944059,19.586893,1.320815,0.028907,0.160946,0.802947,0,COMPLETE
2,2,-1.999991,9.909911e+08,2026-07-24 16:30:27.535013,2026-07-24 16:31:14.191756,0 days 00:00:46.656743,1.316395,1.043536,0.080370,39.236004,0.266019,34.179151,0.731829,35.061739,0.882970,0.030811,0.000003,0.348338,0,COMPLETE
3,3,-1.999964,9.649126e+08,2026-07-24 16:30:27.573045,2026-07-24 16:31:11.878121,0 days 00:00:44.305076,1.373293,1.125612,0.354198,48.183710,0.943400,2.960239,1.207550,2.982179,0.341689,0.079845,0.000348,0.463773,0,COMPLETE
4,4,-1.999991,9.909911e+08,2026-07-24 16:31:11.815021,2026-07-24 16:31:56.243554,0 days 00:00:44.428533,0.805803,0.424103,0.014436,8.960984,0.594466,70.119456,0.732007,1.176280,0.291272,0.001066,20.790542,0.331606,0,COMPLETE
5,5,-1.999982,9.821430e+08,2026-07-24 16:31:11.886848,2026-07-24 16:31:55.704752,0 days 00:00:43.817904,0.021098,1.173871,0.659393,46.953900,1.440453,42.596460,1.460329,25.227867,1.141617,0.083312,0.000011,1.402052,0,COMPLETE
6,6,-1.999882,8.943098e+08,2026-07-24 16:31:13.804557,2026-07-24 16:31:59.949222,0 days 00:00:46.144665,0.010446,0.140764,0.010780,40.044402,1.207674,1.096788,0.255359,23.261897,0.142289,0.098695,0.000185,1.237080,0,COMPLETE
7,7,-1.999991,9.909911e+08,2026-07-24 16:31:14.201272,2026-07-24 16:32:00.313863,0 days 00:00:46.112591,0.811823,0.229878,0.731168,15.879727,0.899141,42.660333,1.136566,3.369124,0.943413,0.003371,0.007501,1.208577,0,COMPLETE

## Results

So it takes 45 seconds for a gpu to run it and I can 4 in a row

It takes 4 min for a cpu to run it but I can do 32 in a row

In 4 min I can have 5 gpu runs so we get 20 trials with gpu compared to 32 with cpu

# 1,000,000 steps and N is 100 and timeout is 60

## 4 GPU

In [6]:
trial_id = 435860
output_path = os.path.join("output", str(trial_id))
with open(os.path.join(output_path, "config.json"), "r") as f:
    config = json.load(f)
print("Config:", config)
df = pd.read_csv(os.path.join(output_path, "trials_results.csv"))
print(df.shape)
df[:10]

Config: {'steps': 1000000, 'N': 100, 'target_node_count': 10, 'timeout': 60}
(4, 20)

,number,values_0,values_1,datetime_start,datetime_complete,duration,params_between_rest_spread,params_c_spread,params_c_val,params_input_force,params_k_between_spread,params_k_between_val,params_k_wall_spread,params_k_wall_val,params_m_spread,params_m_val,params_ridge_alpha,params_wall_rest_spread,system_attrs_NSGAIISampler:generation,state
0,0,-1.999999,9.990917e+08,2026-07-24 16:43:04.781955,2026-07-24 16:50:47.533529,0 days 00:07:42.751574,0.034705,0.049379,0.337644,44.484985,1.456874,81.716836,1.460177,2.917159,1.192957,0.010237,0.030002,0.142435,0,COMPLETE
1,1,-1.999999,9.990917e+08,2026-07-24 16:43:04.876369,2026-07-24 16:50:36.292860,0 days 00:07:31.416491,1.108165,0.407587,0.010367,38.859870,1.454011,27.355862,0.206714,1.128687,1.483025,0.024694,0.114171,1.001293,0,COMPLETE
2,2,-1.999997,9.972801e+08,2026-07-24 16:43:04.900403,2026-07-24 16:50:15.849867,0 days 00:07:10.949464,0.849324,1.160813,0.034223,31.959236,0.794880,22.305440,1.161233,37.091977,0.582108,0.078824,75.754233,1.047383,0,COMPLETE
3,3,-1.999987,9.874327e+08,2026-07-24 16:43:04.900831,2026-07-24 16:50:24.504479,0 days 00:07:19.603648,0.424408,0.590331,0.063280,21.303103,1.391697,5.385670,0.426572,1.518312,0.380419,0.049628,0.016769,0.994054,0,COMPLETE

## Results

So it takes 45 seconds for a gpu to run it and I can 4 in a row

It takes 4 min for a cpu to run it but I can do 32 in a row

In 4 min I can have 5 gpu runs so we get 20 trials with gpu compared to 32 with cpu